"""fish tickets

Revision ID: 6a59b01b8943
Revises: 
Create Date: 2023-05-22 17:36:34.829737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a59b01b8943'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('tide_am_pm', sa.Boolean(), nullable=True),
    sa.Column('set_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4'
    )
    op.create_table('ticket_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('landing_num', sa.String(length=20), nullable=True),
    sa.Column('permit_num', sa.String(length=255), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('landing_time', sa.DateTime(), nullable=True),
    sa.Column('ticket_notes', sa.String(length=255), nullable=True),
    sa.Column('ticket_entry_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('landing_num'),
    mysql_charset='utf8mb4'
    )
    op.drop_table('conversation_messages')
    op.drop_table('conversation_dialogue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_dialogue',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('from_user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shared_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('subject', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('trash', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('draft', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('unread', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('conversation_messages',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('conversation_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('ticket_ticket')
    op.drop_table('ticket_entry')
    # ### end Alembic commands ###
